name: cinema
services:

  backend_server:
    container_name: backend
    build: ./backend
    volumes:
      - ./backend:/app/backend
    environment:
      - PORT=8000
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=postgres_server
      - POSTGRES_PORT=5432
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - postgres_server

  frontend_server:
    container_name: frontend
    build: ./frontend
    volumes:
    - ./frontend:/app/frontend
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
    restart: always
    depends_on:
      - backend_server

  postgres_server:
    container_name: db
    image: pgvector/pgvector:pg16
    restart: always
    ports:
     - 5432:5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
     - ./init.sql:/docker-entrypoint-initdb.d/init.sql
     - db-data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=david@email.com
      - PGADMIN_DEFAULT_PASSWORD=abcdef12345
      - PGADMIN_LISTEN_PORT=5050
      - PGADMIN_CONFIG_PROXY_X_HOST_COUNT=1
      - PGADMIN_CONFIG_PROXY_X_PREFIX_COUNT=1
    ports:
      - "5050:5050"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres_server
      
volumes:
  db-data:
  pgadmin-data: