name: cinema
services:
  db:
    container_name: db
    hostname: db
    image: pgvector/pgvector:pg16
    ports:
     - 5432:5432
    restart: always
    environment:
      - POSTGRES_DB=vectordb
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpwd
    volumes:
     - ./init.sql:/docker-entrypoint-initdb.d/init.sql
     - ./postgres/data:/var/lib/postgresql/data
  # backend:
  #   container_name: backend
  #   build : ./backend
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - ./backend:/cinema/backend
  #   restart: always